"""empty message

Revision ID: 2731655ba8ba
Revises: 602a791ac296
Create Date: 2019-09-29 17:49:46.206415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2731655ba8ba'
down_revision = '602a791ac296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'published')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('published', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
