"""empty message

Revision ID: 602a791ac296
Revises: 7c75434c1d78
Create Date: 2019-09-29 17:33:04.946301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602a791ac296'
down_revision = '7c75434c1d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('visit_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'visit_time')
    # ### end Alembic commands ###
