"""empty message

Revision ID: df91daa507f9
Revises: 9c95f42b45ed
Create Date: 2019-09-29 10:09:43.583872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df91daa507f9'
down_revision = '9c95f42b45ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adventures', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('adventure_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'adventure_id')
    op.drop_column('adventures', 'trip_id')
    # ### end Alembic commands ###
